# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "feat/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      # Workaround from https://github.com/dotnet/aspnetcore/issues/65391#issuecomment-4040414045
      - name: Install SSL Certificates
        run: |
          export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:${SSL_CERT_DIR:-/usr/lib/ssl/certs}"
          dotnet dev-certs https --trust

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test with coverage
        run: dotnet dotnet-coverage collect "dotnet test --no-build --verbosity normal" -f cobertura -o tests/coverage.xml --settings coverage.runsettings

      - name: Generate coverage report
        run: dotnet reportgenerator -reports:tests/coverage.xml -targetdir:coveragereport -reporttypes:MarkdownSummaryGithub

      - name: Coverage summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
